# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishd',
            new_name='published',
        ),
    ]
